server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Planty

adafruit:
  api:
    url: https://io.adafruit.com

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:604800000}   # 기본값 7일

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

fcm:
  firebase_config_path: ${FIREBASE_CONFIG_PATH}

agent:
  base-url: ${AGENT_URL}

encryption:
  secret: ${ENCRYPTION_SECRET_KEY}